[FEATURE] 인기곡 랭킹 기능 구현 중간점검
nerd-team-1/favorite-18-server pull request #27
Opened 2024-06-23 06:31 UTC by BellaChooi

## 📝 PR Summary
entity를 생성하고 랭킹 조회를 구현하였습니다,

#### 🌲 Working Branch
#15 

#### 🌲 TODOs

- [ ]  Entity 생성
- [ ] 인기곡 순위 랭킹순으로 조회
- [ ] 상세페이지 접속 횟수 세기
- [ ]  1일 1회 데이터 저장 구현
- [ ]  노래방 기기별 노래 번호 조회

### Related Issues
 작업량은 적지만 협업자체가 처음이라 하나하나 분석하며 하느라 시간이 오래 걸렸습니다..
다른 작업들도 열심히 진행해보겠습니다. 부족하지만 피드백 부탁드려요:)

2024-06-23 13:10 UTC, JakePark929 reviewed
제가 확인할 수 있는 부분은 코멘트 드렸구요!
오늘 알려드린 스웨거로 데이터 오는거 테스트 해보시고 말씀 부탁드립니다.
테스트 코드 추가하신 점 너무 잘하셨구요 :)

서영님은 종원님 코멘트도 같이 받아서 어프루브 하겠습니다.
@donsonioc2010 종원님도 코멘트 부탁해요~

2024-06-23 13:10 UTC, JakePark929 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankController.java
> +    public ApiResponse<RankDto> getRankAll(@PathVariable LocalDateTime today, String machineType) {
PathVariable 어노테이션의 용도를 확인해 보시고, RequestParam 어노테이션을 활용해보면 어떨까요? 
오늘 회의 때도 보여드렸지만, 컨트롤러에서 어떤 데이터를 어떻게 받을 지에 대한 방법은 무수히 많고, 
주로 url 맵핑과 요구 사항에 맞춰 정해집니다. :)

2024-06-23 13:10 UTC, JakePark929 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/converter/RankConverter.java
> +       /* public Rank toEntity(Song songEntity, RankAddRequest request) {
쓰지 않는 코드는 프로덕션 코드에서 제외하는 것이 좋습니다.
만약 꼭 필요한 코드인데 주석 할 경우 주석으로 메모를 남겨두고, 
언제 어떻게 처리할 지 적어 두는 것이 코드 유지 보수에 도움을 줍니다 :)

2024-06-23 13:10 UTC, JakePark929 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RankService.java
> +        ValueOperations<String, Object> values = redisTemplate.opsForValue();
만약 레디스를 사용한다면 데이터를 불러오는 로직은 비즈니스 클래스에서 처리해주는 것이 어떨까요?
사실 비즈니스 클래스를 추가한 용도가 이런 외부 프로그램과의 연결을 처리해주기 위함입니다.

우선 이대로 두고 추후에 함께 고민해봅시다!

2024-06-23 13:10 UTC, JakePark929 commented on core/core-api/src/test/java/com/nerd/favorite18/service/RankServiceTest.java
> +public class RankServiceTest {
저도 마침 테스트 코드의 필요성을 절실히 느끼고 있었던 참이라
테스트 코드 추가하신 점 너무 잘하셨습니다 👍

2024-06-23 13:10 UTC, JakePark929 commented on storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/ranking/entity/Rank.java
> +    private LocalDateTime rankDate;
@donsonioc2010 종원 님이 먼저 의견 주셨는데 LocalDate 로 하면 불 필요한 시간 정보를 제외할 수 있어 보입니다.

2024-06-23 13:48 UTC, donsonioc2010 reviewed
정말고생많았습니다 서영님!

보면서 바로바로 생각나는 것들을 적어봐봤습니다.  변경이 필요할 것 같다 생각되는 부분들도 존재하여, 바로 Approve는 힘들것 같긴하지만 그래도 정말 잘하신것 같아요 :)

1차 완성일까지 페이스조절하면서 잘 해보면 좋을것 같아용

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/RedisConfig.java
> +        redisTemplate.setDefaultSerializer(new StringRedisSerializer());
이런설정은 처음봐서 질의 드립니당.

`new StringRedisSerializer()`를 매번 객체 생성해서 넣어줘야 하는 부분인가용??

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankController.java
> +    public ApiResponse<RankDto> getRankAll(@PathVariable LocalDateTime today, String machineType) {
아까 회의때 말씀을 드렸지만.. :)
1. MachineType이 저희가 Enum으로 지정한 값이 아닌 다른 값이 들어오는 경우 어떻게 되나요?
2. 위의 중언님 말처럼 `@PathVariable`어노테이션이 어떤 역할을 하는지, 어떻게 사용해야하는지를 한번 확인해보셔야 할 것 같아요 :)
3. today와 RankEntity까지 연결되는 얘기지만, 시간이 중요하지 않고, 날짜만 중요하다면 `LocalDate`라는 타입의 사용을 고려해 보는것도 좋을 것 같습니다.

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RankService.java
> +    public void increaseSearchCnt(Long songId) {
해당 메소드는 현재 사용중인 부분일까요?

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/test/java/com/nerd/favorite18/service/RankServiceTest.java
> +    RankService rankService;
접근제어자가 필요하다 생각됩니다.

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/test/java/com/nerd/favorite18/service/RankServiceTest.java
> +    EntityManager em;
EntityManager를 주입받아야 할 이유가 있으실까요?

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/test/java/com/nerd/favorite18/service/RankServiceTest.java
> +    }
테스트 케이스에서 검증을 하는부분이 필요하다 생각이 드네용 :)

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/test/java/com/nerd/favorite18/service/RankServiceTest.java
> +    }
해당 메소드는 Test케이스는 아닌것 같습니다. `@Test`어노테이션의 역할을 한번 확인해볼 필요가 있을꺼 같아요 :)

2024-06-23 13:48 UTC, donsonioc2010 commented on storage/db-core/build.gradle
> +    testImplementation project(path: ':core:core-api') // querydsl
혹시 testImplementation으로 core-api를 추가한 이유가 있으실까요?

2024-06-23 13:48 UTC, donsonioc2010 commented on storage/db-core/build.gradle
> +
coreApi에서 Redis를 추가하고, 여기서 또 추가할 필요가 있으실까요?

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RankService.java
> +        return (searchCnt != null) ? searchCnt.longValue() : 0L;
searchCnt가 이미 `Long`타입인거같은데,  longValue()로 반환해야 할 이유가 있으실까용 ??

2024-06-23 13:48 UTC, donsonioc2010 commented on core/core-api/build.gradle
> +    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-data-redis', version: '3.3.1'
이건 시간될때 Redis를 담당하는 모듈을 만들어 보도록 하겠습니다 ㅎ;;

2024-06-23 13:48 UTC, donsonioc2010 commented on storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/ranking/entity/Rank.java
> +import jakarta.persistence.*;
WildCard의 경우 저는 사용을 지양하고 있는데용. 저는 다른이유이지만, 제 멘토님은 멘토님대로 생각했던 아티클을 드려보고자합니다.

보고서는, 서영님도 서영님만의 생각을 한번 가져보면 좋을것 같아요 :)

[아티클 링크](https://careerly.co.kr/comments/83968)

2024-06-23 13:48 UTC, donsonioc2010 commented on storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/ranking/entity/Rank.java
> +    private Long searchCnt;
`long`타입의 경우에는 객체가 생성될 때, Null인 경우 DefaultValue로 0이 설정됩니다.
`Long` 타입의 경우, Null이 들어가게 되는데요, 추후 해당 부분에서 NPE가 발생할지 여부에 대해서 생각해 보셨을까용? 

이건 위의 컬럼인 `rank`도 동일해 질 것 같네용.

서영님 코드를 보다보니 제코드도 다시봐야할것 같아졌습니다 🤣

2024-06-28 01:12 UTC, donsonioc2010 reviewed
고생하셨어용. 충돌이 발생하는데 아마 제가 CI, CD를 Merge해서 그럴것 같아요.

추후 충돌 해결도 같이 해놓으셔야 할 것 같습니당 :)

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankController.java
> +    public ApiResponse<List<RankDto>> getRankAll(@PathVariable LocalDate today, MachineType machineType) {
해당 부분 `@PathVariable`은 지난번에 중언님이 코멘트 드렸던걸로 기억이 납니다.

이후 확인해보셨던게 있으실까요?

또한 MachineType의 경우에도 어떻게 파라미터를 받는 것인지 알려주실수 있으실까요?

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
> +public class RankRadisController {
흠..지금보니 `RankRedisController`와 `RankController`로 구분할 필요가 있나 싶네요.

두개가 같은 Mapping을 쓰는거면 같이 관리하고, Service를 분리하는것도 괜찮아 보입니다.

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
> +    public void setSongCount(@RequestBody HashMap<String, String> body) {
`@RequestBody`로 받는것은 좋은데, 해당 body에 무슨 값이 들어오는지 구분이 불가능하지 않을까요?

단일필드인지, 리스트인지 등등이요

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
> +        String searchCnt = body.get("searchCount").toString();
만약 body에 해당 규칙을 지키지 않고, 실제 존재하지 않는 값이 들어오는 경우 어떻게 되나요?

즉 `songId`가 Body에 없는 상황 등이요.

한번 `Spring-Validation`에 대해서도 같이 알아보시면 좋지 않으실까 합니다.

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
> +    public String getSongCount(@PathVariable Long songId) {
👍

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
> +        return ResponseEntity.ok("Song count incremented for songId: " + songId);
이런건 잡담 인데요, 저는 이런방식을 선호합니다. 다양한 방식을 알고 계시면 좋을 듯 해서 기록해둡니당 

참고로 문자열은 따로 변수같은걸로 빼서 많이 해둡니다. 그래서 보통 변수명이 들어가는 편이에용 :)
```suggestion
        return ResponseEntity.ok(String.format("Song count incremented for songId: %d", songId));
```

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RedisRankService.java
> +    private static final String REDIS_KEY_PREFIX = "rank:songs:";
👍

2024-06-28 01:12 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RedisRankService.java
> +        String key = REDIS_KEY_PREFIX + songId.toString();
이런 중복되는 KeyGenerate하는 코드는 메소드로 추출이 가능할것 같아요.

2024-06-28 01:12 UTC, donsonioc2010 commented on storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/ranking/repository/RankRepository.java
> +    Optional<List<Rank>> findByRankDateAndMachineTyperOrderBySearchCntDesc(@Param("rankDate") LocalDate rankDate, MachineType machineType);
Optional의 사용 방법을 알아보면 좋을 듯 합니다.

추가적으로, Optional내부에서 Collection과 Array를 반환형으로 사용하는것은 좋지 않은 방식인건 미리 말씀드려보겠습니다 ㅎㅎ;

또한 JPA에서 `List<Entity>`, `Optional<List<Entity>`, `Entity`로 할 시 어떤 결과가 반환되는지 확인해 보셔야 할 것 같습니다. (저도 처음에 JPA쓸때 혼란이 많이 왔었어요)

2024-06-28 01:25 UTC, donsonioc2010 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RedisRankService.java
> +        String key = REDIS_KEY_PREFIX + songId.toString();
왠지 생각해보니,  ValueOperations<String, String> values 요친구만 쓰는거라면, 생성자에서 미리 받아놓는것도 괜찮겠네요

2024-06-28 01:46 UTC, JakePark929 requested changes
서영님! 열심히 참여해 주시고 계셔서 늘 감사합니다 :)

종원님이 코드 리뷰 잘 해주셨는데요.
다만 현재 까지의 commit 이 기존 리뷰 사항에 대해 적용이 되지 않은 채 
다음으로만 진행이 계속 되는 부분이 일부 있습니다.

제 생각에는 완료 되지 않은 상태에서 계속 새로운 기능을 추가해 나가는 것보다
단순히 데이터를 DB에 추가하고 조회하는 작은 기능이라도 요구 사항을 정확히 수행해 나가는 것이 
서영님의 성장에도, 저희 모두에게도 좋아 보입니다.

결론은 db에 랭킹 데이터가 정확히 추가되는지, 단순한 로직부터 동작 여부를 확인해서
프로덕트해 추가해 나가도록 합니다! 배치와 같은 큰 작업은 새로운 이슈를 등록하셔서 진행하셔도 충분합니다 :)

#27 PR은 저희가 동작 진행해보고 수정할 부분들 확인해서 서영님께 전달드리고 수정이 완료되면 머지하도록 하겠습니다.

2024-06-28 02:38 UTC, JakePark929 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
> +public class RankRadisController {
url 주소도 조금 체계적으로 정리할 필요가 있어 보입니다.
Redis 와 동작하는 기능들도 요구사항 정의서에 추가하셔서 url 을 정리해보는 것은 어떨까요?

2024-06-28 03:28 UTC, JakePark929 commented on core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
> +public class RankRadisController {
url 주소도 조금 체계적으로 정리할 필요가 있어 보입니다.
Redis 와 동작하는 기능들도 요구사항 정의서에 추가하셔서 url 을 정리해보는 것은 어떨까요?

예를 들어 rank 도메인은 api/v1/rank 만 해도 충분해 보입니다!
그리고 아래 Redis 와 동작하는 mapping 도 조금 축약할 수 있을 것 같아요!

2024-06-28 05:43 UTC, JakePark929 approved these changes

2024-06-28 05:44 UTC, merged